//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Bishop : ChessPiece{

    public override BoardSpace[] GetAvailableSpaces()
    {
        List<BoardSpace> availableSpaces = new List<BoardSpace>();

        //GET BASE MOVE AND CAPTURE SPACES
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.FrontLeft));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.FrontRight));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.BackLeft));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.BackRight));
        
        return availableSpaces.ToArray();
    }
}


