//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class King : ChessPiece{

    public override BoardSpace[] GetAvailableSpaces()
    {
        //Debug.Log (activeSpace.getSpace(SpaceDirection.Front,teamColor));
        List<BoardSpace> possibleSpaces = new List<BoardSpace>();
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.FrontLeft, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.Front, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.FrontRight, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.Left, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.Right, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.BackLeft, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.Back, teamColor));
        possibleSpaces.Add(board.getAdjacentSpace(currentSpace, SpaceDirection.BackRight, teamColor));
        return possibleSpaces.ToArray();
    }


}


