//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Rook : ChessPiece{

    public override BoardSpace[] GetAvailableSpaces()
    {
        List<BoardSpace> availableSpaces = new List<BoardSpace>();
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.Front));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.Right));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.Back));
        availableSpaces.AddRange(GetAvailableInDirection(SpaceDirection.Left));
        return availableSpaces.ToArray();
    }

}

