//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;


public class WhiteMaster : MonoBehaviour {
	
	public bool goesFirst = true;
	///<summary>Array for tracking the number of captured pieces, by type.
	/// PieceCaptured: Index# 
	/// Pawn : [0];
	/// Rook: [1];
	/// Knight: [2];
	/// Bishop: [3];
	/// Queen: [4]; 
	/// </summary>		
	public int[] whitePiecesCaptured = {0,0,0,0,0};

	// Use this for initialization
	void Start () {
	}
	
	// Update is called once per frame
	void Update () {
		
	}
}
